### ISSUE TITLE
Undefined and not used tool_certificate\plugin_manager class

### ISSUE THREAD

**Issue by volodymyrdovhan** [fmido88/moodle-local_devassist#1]
Hello,
I found undefined and not used tool_certificate\plugin_manager class in local/devassist/classes/form/capabilities.php file:

![image](https://github.com/user-attachments/assets/0b4a816d-a550-49d3-aa0f-666ff09ab1ab)

**Comment by fmido88** [comment]
Due to autocomplete in the text editor.

Solved
