### ISSUE TITLE
Incorrect dataroot usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [fmido88/moodle-local_devassist#3]
Hello,
your plugin stores the plugins.zip archive directly in the moodledata folder:
![image](https://github.com/user-attachments/assets/308561c8-c82f-4420-828d-ffc887ab5992)

It is better to use the temporary plugin folder or temporary request folder in your case.

Something like:
`$tempdir = make_temp_directory('local_devassist');`
or 
`$tempdir = make_request_directory();`

**Comment by fmido88** [comment]
$tempdir used instead
