### ISSUE TITLE
Namespace collisions

### ISSUE THREAD

**Issue by volodymyrdovhan** [fmido88/moodle-local_devassist#4]
Hello,

According to Moodle standards, all custom classes that are not part of the core API should be placed in the 'classes/local' folder to avoid potential namespace collisions. You can refer to the guidelines here:
[Namespace Collisions - Moodle Plugin Checklist](https://moodledev.io/general/community/plugincontribution/checklist#namespace-collisions)

Additionally, please review the rules for level 2 namespaces:
[Level 2 Namespaces](https://moodledev.io/general/development/policies/codingstyle#rules-for-level2)

**Comment by fmido88** [comment]
I checked that its ok to use custom classes in level 1, I'm not sure which class may cause the problem
![image](https://github.com/user-attachments/assets/30cc1150-47ad-4d33-a682-e4a58665f0d4)
As mentioned custom classes could be placed on level 1 
If it is not ok I'll move all of them to classes/local
